# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PaomAds' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PaomAds

  target 'PaomAds-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PaomAdsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'PaomAds-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for PaomAds-tvOS

  target 'PaomAds-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

pod 'RNVectorIcons', :path => 'node_modules/react-native-vector-icons'
